server:
  port: 8083
  servlet:
    context-path: /
    encoding:
      force-response: true

spring:
  application:
    name: demo2

  datasource:
    url: jdbc:mysql://localhost:3306/jmdb
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50  # 5 → 50 이상으로 확장
      minimum-idle: 10
      idle-timeout: 10000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        show_sql: true
        id:
          new_generator_mappings: false